# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-10 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student_identification',
        ),
        migrations.RemoveField(
            model_name='student',
            name='max_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='max_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_identification',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
